# Generated by Django 5.2 on 2025-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskDashboard', '0004_task_assigned_to_task_priority_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Project Manager'), (3, 'Developer')], default=3, null=True),
        ),
    ]
